tba_api_key: DV7ILacUNlmvVF126hDVNwINg15LpvwZ004JxrwpE49ftCmlD8XdeZCItp92JoYL
event_id: 2022tuis2
highlighted_team: 7285
data_dir: D:\Workspace\cs-workspace\Sneaky-Scout\QR-Reader\ScoutDatas
scripts_dir: D:\Workspace\cs-workspace\Sneaky-Scout\DataAnalyzer\PythonScripts